### ISSUE TITLE
Connect to web URL

### ISSUE THREAD

**Issue by nekcorp** [carsonyl/pypac#13]
Hi,

I need to use Google API to get json info file and I must use proxy in order to connect in internet. On my computer I use .pac file to connect in internet as describre [here](http://pypac.readthedocs.io/en/latest/about_pac.html#wpad).

The script I used it is : 
```
from urllib2 import urlopen
import json

def get_jsonparsed_data(url):
    response = urlopen(url)
    data = response.read().decode("utf-8")
    return json.loads(data)

url = ("http://maps.googleapis.com/maps/api/geocode/json?"
       "address=googleplex&sensor=false")
print(get_jsonparsed_data(url))
```
When we want use proxy with urllib.open method the script syntax is :  
```
urllib.urlopen(url[, data[, proxies[, context]]])
```
as desribe in the [documentation](https://docs.python.org/2/library/urllib.html#urllib.urlopen).

How can insert pypac into my script in order to use my proxy (pac file) ?

Thanks a lot for your help.

**Comment by carsonyl** [comment]
Instead of using `urllib` from the standard library, use PyPAC's `PACSession`. PyPAC is based on [Requests](http://docs.python-requests.org/en/master/), which can replace urllib(2) entirely.

If you've looked inside your PAC file and know the correct proxy server to use, and you're okay with hard-coding the proxy into your code, you can just put it directly into your `urllib.urlopen()` calls instead of rewriting your code to use PyPAC/Requests.
