### ISSUE TITLE
pypac + js2py uses a lot of memory

### ISSUE THREAD

**Issue by genotrance** [carsonyl/pypac#20]
I am working on [Px](https://github.com/genotrance/px), a proxy server that does NTLM/Kerberos authentication and I recently added pypac to support PAC files. 

Before pypac, Px was 6MB executable with PyInstaller and using around 10MB of RAM per process. After pypac, it's at 14MB and using 140MB of RAM per process. This is all on Windows.

I know pypac in itself only uses around 10-20MB of RAM but the dependency on js2py is 120MB worth. And this adds up quickly since Px can run in multiple processes to improve scale.

Long story short, at least on Windows, there's JScript which is free and available to execute the JS functions so depending on js2py seems relatively expensive. Using JScript along with PAC JS code from [here](https://github.com/TooTallNate/node-pac-resolver), you have a simpler mechanism to process the PAC file.

No doubt, it might be slower (I plan on testing it) to do the check for each URL since you need to spawn a cscript.exe process for each call but RAM and size wise, it might be worth it.

I'm curious what your thoughts are on this matter.

**Comment by carsonyl** [comment]
I wasn't aware of any alternative to js2py at all, so this JScript idea is intriguing. Up until now, PyPAC's resource usage hasn't been something I needed to consider - I didn't expect anyone to use it in multiprocess scenarios either. I hope that you're seeing 120MB usage only when a PAC is in use, instead of just by importing js2py.

I don't have experience with JScript, so I'm definitely interested in your results. Perhaps PyPAC could conditionally avoid js2py on Windows.

Another idea: perhaps Px can have one process dedicated to PAC discovery, parsing, and global state, with the lightweight proxy server processes querying it. It makes sense to have global state for the PAC anyway.

**Comment by genotrance** [comment]
So even simply doing an `import js2py` in a Python REPL loads up 130MB of RAM. Python starts out at ~5MB. So even if Px never uses pypac, it's using the extra RAM.

Meanwhile, I found an even better way to do this - using winhttp.dll which does all the discovery and resolution.

https://gist.githubusercontent.com/mgeeky/8960f4fa3f9462ae7bcd6db4ce42a8d3/raw/f44041bab242a64c54f161f67d67ee6b4e119a45/check-proxy.py

No doubt it is Windows only and few are fans of ctypes but it uses 5.5MB of RAM so who cares.

**Comment by carsonyl** [comment]
> So even simply doing an import js2py in a Python REPL loads up 130MB of RAM. Python starts out at ~5MB. So even if Px never uses pypac, it's using the extra RAM.

That's bad. As a first step, I'll defer `import js2py` until it's actually needed.

**Comment by genotrance** [comment]
Just tried this out and pypac now uses 21MB of memory. I plan on going back to using pypac in Px since it is cross-platform and will help expand support over to Linux. Plus I'd take leverage any day.

Thanks for attending to this issue and your ongoing efforts on pypac!

**Comment by carsonyl** [comment]
Unfortunately, #32 reports a memory leak, so maybe don't hurry back to PyPAC until we figure it out. :)

**Comment by genotrance** [comment]
Thanks for the update - will keep an eye out, but expect to get to this after a while since there's a long path to Linux support.
