### ISSUE TITLE
Question about Windows PAC file

### ISSUE THREAD

**Issue by BoboTiG** [carsonyl/pypac#25]
Hello,

I was testing the PAC handler on Windows. When retrieving the file from the registry and it is a `file://`, this will not work: `file://e:\\proxy.pac`. To make it work, we must convert to `file://e:/proxy.pac`.

My question is: is it always in the good format in the registry? In your tests, you are not testing this form. Note that there is no issue here, I was just asking to prevent any regression in our product using your module :)

**Comment by carsonyl** [comment]
That's a good point. I just did a quick test: turns out Windows Internet Options does no validation on this field. Any input is stored as-is in the registry key. https://blogs.msdn.microsoft.com/ie/2006/12/06/file-uris-in-windows/ suggests `file://e:\proxy.pac` isn't valid for Windows file URLs, but [this post](https://blogs.msdn.microsoft.com/freeassociations/2005/05/19/the-bizarre-and-unhappy-story-of-file-urls/) classifies it as 'legacy'.

Looking more closely at https://en.wikipedia.org/wiki/File_URI_scheme, it looks like PyPAC incorrectly accepts `file://c:/foo/bar.pac`, when it should actually be `file:///c:/foo/bar.pac`.

**Comment by BoboTiG** [comment]
Thank you for the complete answer :)
I let you close the issue, I do not know if you plan to change the current behavior.
