### ISSUE TITLE
Support keywords: HTTP, HTTPS, SOCKS4, SOCKS5

### ISSUE THREAD

**Issue by carsonyl** [carsonyl/pypac#41]
Currently, the following keywords are recognized from the PAC: `DIRECT` `PROXY`, `SOCKS`.

[Mozilla's PAC file doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_(PAC)_file) says Firefox supports more keywords: `HTTP`, `HTTPS`, `SOCKS4`, `SOCKS5`.

Proposed interpretation:

- `HTTP host:port` -> `http://host:port` (synonym for `PROXY`)
- `HTTPS host:port` -> `https://host:port`
- `SOCKS host:port` -> `socks4://host:port`
- `SOCKS5 host:port` -> `socks5://host:port`

The `SOCKS` keyword is already assumed by default to be `socks5://`.

**Comment by ibarrond** [comment]
+1! `HTTPS` is a keyword I'm looking forward to have

**Comment by SeyfSV** [comment]
Hi @ibarrond, 
I added HTTPS in #44, but there is [issue](https://github.com/urllib3/urllib3/issues/1662) with urllib3 library (you can try to fix it with this [patch](https://github.com/SeyfSV/urllib3/commit/ec7c6390d92cdee36ece3b6f54ca0d0d88bf7ced) ).
Also I had issue with PAC file provider, that does not return HTTPS for default User-Agent. It can be fixed by assigning Firefox User-Agent for example ([look](https://github.com/carsonyl/pypac/pull/44#issue-306289090))
